{{- if eq .Values.loadBalancer.type "alb" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    {{- include "boldbi.labels" . | nindent 4 }}
  name: bold-ingress
{{ include "boldbi.namespace" . | indent 2 }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: {{ .Values.loadBalancer.scheme | default "internet-facing" }}
    alb.ingress.kubernetes.io/target-type: {{ .Values.loadBalancer.targetType | default "ip" }}
    alb.ingress.kubernetes.io/healthcheck-path: /health-check
    {{- if .Values.loadBalancer.affinityCookie.enable }}
    alb.ingress.kubernetes.io/auth-session-cookie: bold.k8s.pod.id
    alb.ingress.kubernetes.io/auth-session-timeout: "{{ $.Values.loadBalancer.affinityCookie.affinityCookieExpiration }}"
    {{- end }}
    {{- if and .Values.loadBalancer.ssl.enable (eq .Values.loadBalancer.ssl.tls "arn") }}
    alb.ingress.kubernetes.io/certificate-arn: "{{ $.Values.loadBalancer.ssl.arn }}"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    {{- end }}
    {{- if .Values.loadBalancer.groupName }}
    alb.ingress.kubernetes.io/group.name: "{{ $.Values.loadBalancer.groupName }}"
    {{- end }}
    {{- range $key, $value := .Values.loadBalancer.albIngressAnnotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
  {{- if and .Values.loadBalancer.ssl.enable (eq .Values.loadBalancer.ssl.tls "secret") }}
  {{- if eq (split ":" .Values.appBaseUrl)._0 "https" }}
  tls:   
    {{- if .Values.loadBalancer.multipleHost }}
    {{- range $host := .Values.loadBalancer.multipleHost.hostArray }}
    - hosts:
      {{- range $dns := $host.hosts }}
        - {{ $dns }}
      {{- end }}
      secretName: {{ $host.secretName }}
    {{- end }}
    {{- else }}
    - hosts:
        - {{ (split "/" .Values.appBaseUrl)._2 }}
      secretName: {{ .Values.loadBalancer.singleHost.secretName }}
    {{- end }}
  {{- end }}
  {{- end}}
  ingressClassName: alb
  rules:
  - host: {{ (split "/" .Values.appBaseUrl)._2 }}
    http:
      paths:
      - path: "/etlservice/*"
        pathType: ImplementationSpecific
        backend:
          service:
            name: bold-etl-service
            port:
              number: 6009
      - path: "/bi/api/*"
        pathType: ImplementationSpecific
        backend:
          service:
            name: bi-api-service
            port:
              number: 6005
      - path: "/bi/jobs/*"
        pathType: ImplementationSpecific
        backend:
          service:
            name: bi-jobs-service
            port:
              number: 6006
      - path: "/bi/designer/*"
        pathType: ImplementationSpecific
        backend:
          service:
            name: bi-dataservice-service
            port:
              number: 6007
      - path: "/bi/*"
        pathType: ImplementationSpecific
        backend:
          service:
            name: bi-web-service
            port:
              number: 6004
      - path: "/api/*"
        pathType: ImplementationSpecific
        backend:
          service:
            name: id-api-service
            port:
              number: 6001
      - path: "/ums/*"
        pathType: ImplementationSpecific
        backend:
          service:
            name: id-ums-service
            port:
              number: 6002
      - path: "/*"
        pathType: ImplementationSpecific
        backend:
          service:
            name: id-web-service
            port:
              number: 6000
      - path: "/aiservice/*"
        pathType: ImplementationSpecific
        backend:
          service:
            name: bold-ai-service
            port:
              number: 6010
{{- end }}